# Generated by Django 4.2.5 on 2023-11-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0040_orderassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='user',
        ),
    ]
