# Generated by Django 4.2.5 on 2023-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0043_ordercompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercompletion',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='ordercompletion',
            name='worker',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.workerprofile'),
        ),
    ]
