# Generated by Django 4.2.5 on 2023-11-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0044_remove_ordercompletion_worker_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCompletion',
        ),
    ]
