# Generated by Django 4.2.5 on 2024-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0046_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('identity_proof', models.ImageField(upload_to='identity_proofs/')),
                ('driver_license', models.ImageField(upload_to='driver_licenses/')),
            ],
        ),
    ]
