# Generated by Django 4.2.5 on 2024-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0047_deliveryteamapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('driving_license', models.FileField(upload_to='driving_licenses/')),
                ('identity_proof', models.FileField(upload_to='identity_proofs/')),
            ],
        ),
    ]
