# Generated by Django 4.2.5 on 2024-02-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0048_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('gst_number', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(upload_to='vendor_profile_photos/')),
                ('identity_proof', models.FileField(upload_to='vendor_identity_proofs/')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryTeamApplication',
        ),
    ]
