# Generated by Django 4.2.5 on 2024-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0052_vendorproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='edit_history',
            field=models.JSONField(default=list),
        ),
    ]
