# Generated by Django 4.2.5 on 2024-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0055_vendorbio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorBio',
        ),
    ]
