# Generated by Django 4.2.5 on 2024-02-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0058_alter_vendorproduct_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='pincode',
        ),
    ]
