# Generated by Django 4.2.5 on 2024-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0062_remove_vendorproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
