# Generated by Django 4.2.5 on 2024-02-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0063_remove_vendorproduct_category_vendorproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.category'),
        ),
    ]
