# Generated by Django 4.2.5 on 2024-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0064_remove_vendorproduct_quantity_vendorproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
