# Generated by Django 4.2.5 on 2024-03-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0068_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='status',
        ),
    ]
