# Generated by Django 4.2.5 on 2024-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0071_productorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='products',
            field=models.ManyToManyField(through='watersystemapp.OrderItem', to='watersystemapp.vendorproduct'),
        ),
    ]
