# Generated by Django 4.2.5 on 2024-03-14 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0073_remove_deliveryboy_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
