# Generated by Django 4.2.5 on 2024-03-16 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0075_remove_deliveryaddress_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(upload_to='deliveryboy_profile_photos/')),
                ('identity_proof', models.FileField(upload_to='deliveryboy_identity_proofs/')),
                ('driving_license', models.FileField(upload_to='deliveryboy_driving_licenses/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
