# Generated by Django 4.2.5 on 2024-03-16 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0077_remove_deliveryboys_gst_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
