# Generated by Django 4.2.5 on 2024-03-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0079_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.cart'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='delivery_address',
            field=models.TextField(),
        ),
    ]
