# Generated by Django 4.2.5 on 2024-03-31 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0080_orderpayment_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.cart'),
        ),
    ]
