# Generated by Django 4.2.5 on 2024-03-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0081_orderpayment_payment_status_alter_orderpayment_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
